//! Per-profile Claude Code CLI wrappers.
//!
//! Each profile with `surfaces.cli == true` gets a bash script installed at
//! `~/.local/bin/claude-<slug>`. The script exports `CLAUDE_CONFIG_DIR` to
//! the profile's `cli-config/` directory and execs the real `claude` binary.
//!
//! ## How auth isolation works on macOS
//!
//! On macOS Claude Code stores OAuth credentials in the macOS Keychain rather
//! than a file (unlike Linux/Windows where credentials live in
//! `<CLAUDE_CONFIG_DIR>/.credentials.json`). The Keychain service name is
//! `Claude Code-credentials-<hash>` where `<hash>` is the first 8 hex chars
//! of `SHA-256(CLAUDE_CONFIG_DIR)`. So setting a different `CLAUDE_CONFIG_DIR`
//! per wrapper gives each profile its own Keychain entry automatically.
//!
//! This SHA-256 derivation is undocumented Anthropic internals (verified by
//! reverse-engineering Claude Code's internal `V51()` function; relied upon
//! by community tools like diranged/claude-profile and the KMJ-007 gist).
//! If a future Claude Code release changes the hashing scheme, profile
//! isolation silently breaks. The README must surface this risk.

use std::path::Path;

use crate::profiles::Profile;

/// Marker comment used to identify wrappers generated by claude-profiles.
/// `generate` refuses to overwrite — and `remove` refuses to delete — any
/// file at `~/.local/bin/claude-<slug>` that does not contain this string.
pub const MARKER: &str = "# claude-profiles wrapper";

/// Pure: build the bash script body for a wrapper.
/// `cli_config_path` is the absolute, fully-resolved path that
/// `CLAUDE_CONFIG_DIR` will be set to.
pub fn wrapper_script(profile: &Profile, cli_config_path: &Path) -> String {
    format!(
        r#"#!/bin/bash
{marker} — profile: {name} ({id})
export CLAUDE_CONFIG_DIR="{path}"
exec claude "$@"
"#,
        marker = MARKER,
        name = profile.name,
        id = profile.id,
        path = cli_config_path.display(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::profiles::Surfaces;
    use std::path::PathBuf;

    fn fixture() -> Profile {
        Profile {
            id: "deadbeef-0000-0000-0000-000000000000".into(),
            name: "Personal".into(),
            slug: "personal".into(),
            color: "#7C3AED".into(),
            created_at: "2026-05-20T12:00:00Z".into(),
            surfaces: Surfaces {
                gui: false,
                cli: true,
            },
        }
    }

    #[test]
    fn script_starts_with_bash_shebang() {
        let script = wrapper_script(&fixture(), &PathBuf::from("/Users/u/cli-config"));
        assert!(script.starts_with("#!/bin/bash\n"));
    }

    #[test]
    fn script_includes_marker_comment() {
        let script = wrapper_script(&fixture(), &PathBuf::from("/Users/u/cli-config"));
        assert!(script.contains(MARKER));
    }

    #[test]
    fn script_includes_profile_name_and_id_in_header() {
        let script = wrapper_script(&fixture(), &PathBuf::from("/Users/u/cli-config"));
        assert!(script.contains("profile: Personal (deadbeef-0000-0000-0000-000000000000)"));
    }

    #[test]
    fn script_exports_claude_config_dir_with_absolute_path() {
        let script = wrapper_script(
            &fixture(),
            &PathBuf::from(
                "/Users/u/Library/Application Support/claude-profiles/profiles/deadbeef/cli-config",
            ),
        );
        assert!(script.contains(
            r#"export CLAUDE_CONFIG_DIR="/Users/u/Library/Application Support/claude-profiles/profiles/deadbeef/cli-config""#
        ));
    }

    #[test]
    fn script_ends_with_exec_claude() {
        let script = wrapper_script(&fixture(), &PathBuf::from("/Users/u/cli-config"));
        let trimmed = script.trim_end();
        assert!(trimmed.ends_with(r#"exec claude "$@""#));
    }
}
